### ISSUE TITLE
Feature request: Compile for Raspberry Pi (ARM)

### ISSUE THREAD

**Issue by thomas-mc-work** [zaps166/NFSIISE#17]
How much effort would it be to cross compile on an ARM platform to make the game available on the Raspberry Pi?

**Comment by zaps166** [comment]
Hmm, this is x86-32 assembly, so it is not possible to compile for ARM.

The only possibility to run it is to use CPU emulator (e.g. qemu).

Also the x86 assembly could be converted to a C code (e.g. every CPU instruction as a C macro which will do exactly what x86 CPU, use CPU registers as global variables) and then compiled for ARM.

Or use software (if exists) fort static x86->ARM translation.

---

Btw. I haven't used R-Pi since its first version (armv6), so is it possible now to use hardware accelerated OpenGL under X11?

**Comment by zaps166** [comment]
I've started this about 2 years ago, but I didn't finish... Maybe I'll finish it in the future? :)
Then it should run on every non-x86, 32-bit, little-endian CPU :D

**Comment by zaps166** [comment]
I've chosen to finish the old project, almost done :smile:
