### ISSUE TITLE
Deadzone on FFB Wheel

### ISSUE THREAD

**Issue by PPastene** [zaps166/NFSIISE#23]
I have a Logitech Driving Force GT setted at 270° of rotation, and there's a deadzone wich i can't drive very well. Keep in mind that i have managed to run the original game with some patches and this issue is also present as-is. There's a way to fix that?

**Comment by zaps166** [comment]
Is it Windows? Do you have Logitech drivers installed - if yes - check Logitech control panel and adjust the dead zone. Also open config file (on Windows run `open_config.bat`, DON'T edit the `*.template`!), uncomment (remove `#` character) `Joystick0AxisValueShift` and set low value (e.g. `0`). The same for `Joystick1AxisValueShift` for second game controller. Don't forget to save config file. Then run game and check, you can also adjust sensitivity in game.

**Comment by PPastene** [comment]
I try that solution but it still present. Also i've adjust the sensitivity in game but it keeps. When I configure the wheel into 180° the deadzone decreases. Keep in mind that the software that comes with the wheel (Logitech Profiler) only configure per game the degrees of rotation, the pedals acts separately or combined and the force feedback effects, also there's an option to make the game manage those effects on-the-fly

**Comment by PPastene** [comment]
If there's any way to look at the problem and fix it, i'll be grateful to help

**Comment by zaps166** [comment]
> Keep in mind that i have managed to run the original game with some patches and this issue is also present as-is.

Am I understand correctly: Original patched game also has dead zone, right?

---

What about other games? If driver add a dead-zone than game can't do anything (I don't know well the Dinput and Xinput, I use SDL2 for this). If the game add a dead-zone, you should be able to adjust it by modifying `Joystick0AxisValueShift` (not in template file; save and then restart the game).

If it doesn't help I need more info.

**Comment by PPastene** [comment]
Yes, the deadzone comes as-is on the original game, maybe writing a patch for the joystick handling could fix it. Also, I have the Joystick0AxisValueShift at 0 and the UseSpringForceFeedbackEffect at 1, without results.

I'll be uploading a video to show ingame what's happening

**Comment by PPastene** [comment]
https://www.youtube.com/watch?v=JDrByuZcV0U

Here's a video of the deadzone and the force feedback on windows, it doesn't work (look at the logitech profiler options)

**Comment by zaps166** [comment]
Sorry, I forgot how it works :smile: Set `Joystick0AxisValueShift` to high value, e.g. 8000 instead of 0. Accidentally I've got the same wheel - I also forgot about this, because I use DS3 controller, so I can test (Windows 7 x64 on VirtualBox).

`UseSpringForceFeedbackEffect=1` - this doesn't work properly, maybe it is better to disable it (set to `0`)
`WindowsForceFeedbackDevice=1` - if it doesn't work and, set it e.g. to `0` - it is a device index recognized by SDL2, try it yourself.

`Joystick0AxisValueShift=xxx` and `Joystick1AxisValueShift=xxx` - set them only once, don't duplicate it in config file (I can see on youtube description that you set `Joystick0AxisValueShift` twice).

---

I know that the config file should be done better :)
