### ISSUE TITLE
Steam Deck not working

### ISSUE THREAD

**Issue by FireGate13** [zaps166/NFSIISE#83]
I am trying to play this game on my steam deck but there is no audio. can you fix it please?

**Comment by zaps166** [comment]
AFAIK Steam Deck runs modified Arch Linux. Does it use pipewire or pulseaudio? Can you check if you have 32-bit SDL2 and pipewire/pulseaudio libs installed?

**Comment by FireGate13** [comment]
using pactl info command, it shows Server Name: PulseAudio (on PipeWire 0.3.45).  Can you help me how to check the above libraries..?

**Comment by zaps166** [comment]
Ok, so you have PipeWire. I don't know why you don't have sound. Check:
- if you have nfs2se on the audio application list (e.g. `pavucontrol`) and it's not muted
- look if you have `env | grep SDL_AUDIODRIVER`
- install some libs from: `lib32-pipewire`, `lib32-pulse`, `lib32-alsa-lib`
- to use native pipewire with SDL2, run: `SDL_AUDIODRIVER=pipewire nfs2se` (requires `lib32-pipewire`), otherwise it will fallback to pulseaudio (via pipewire, `lib32-pulse`), otherwise it will fallback to alsa (via pipewire, requires `lib32-alsa-lib` and `pipewire-alsa`)

**Comment by FireGate13** [comment]
- no the application is not muted
- nothing in the env output
- unfortunately you cannot install extra libraries on SteamOs (the filesystem is locked, and i am afraid to mess with it)
1. Packages (1) lib32-pipewire-1:0.3.44-1 (it is not installed)
2. warning: lib32-alsa-lib-1.2.6.1-1 is up to date
3. error: target not found: lib32-pulse
- SDL_Init failed: Audio target 'pipewire' not available
- the output of the executable states the following:
ALSA lib conf.c:4110:(config_file_load) cannot stat file/directory /etc/alsa/conf.d
ALSA lib pcm_dmix.c:1032:(snd_pcm_dmix_open) unable to open slave
ALSA lib conf.c:4110:(config_file_load) cannot stat file/directory /etc/alsa/conf.d

**Comment by zaps166** [comment]
* sorry, `lib32-libpulse` - check this package

Something is wrong with 32-bit audio on this OS. Maybe try to run:
`SDL_AUDIODRIVER=pulse nfs2se` ?

**Comment by zaps166** [comment]
The last chance is `SDL_AUDIODRIVER=alsa nfs2se`

Looks like something is wrong with SteamOS libraries (`undefined symbol: _pa_get_library_version` shouldn't happen). Maybe try to download and unpack all needed 32-bit libraries to a directory and set `LD_LIBRARY_PATH` there?

Maybe try also to add "Non-Steam Game" and set compatibility to `Steam Linux Runtime`?

**Comment by FireGate13** [comment]
omg ! i have sound!!!
i did added nf2se as a non steam game and i set compatibility to "steam linux runtime" and it worked!

**Comment by zaps166** [comment]
:1:
