### ISSUE TITLE
controller not detected by game in latest stable release

### ISSUE THREAD

**Issue by AudreyxBelrose** [zaps166/NFSIISE#94]
no matter what i do or how i change the settings, the game does not recognize my controller. it does not work in menus or ingame, and trying to bind the controls in the game's settings yields no response.

the controller previously worked in v1.2.4, and ive gone back and tested it in the older version and it still does work, but it refuses to work in v1.3.0. controller is a current generation xbox controller (makes no difference whether plugged in or via bluetooth).

upon further experimentation with the axes settings, i managed to make the game to constantly scroll down in the menus, but it still doesnt recognize any input in the control map settings.

**Comment by instinctualjealousy** [comment]
Can confirm. No detection whatsoever (Windows 10). Xbox 360 wireless controller, set as preferred controller in Windows.

**Comment by zaps166** [comment]
Maybe SDL2 issue?

**Comment by instinctualjealousy** [comment]
> Maybe SDL2 issue?

It would almost have to be. I also have a 2.4g model of 8BitDo M30 to test. Being it was primarily designed for the Genesis Mini, it has a weirdly implemented DirectInput mode- because of this, it doesn't work perfectly as-is with a lot of things and doesn't have any SDL2 maps from what I know. It does work barring a minor issue, however, and I was able to map all the buttons in game. The 2.4g model also can be engaged in an XInput mode (undocumented, unlike the Bluetooth model) that uses the VID/PID pairs of an official wired Xbox 360 controller. In this mode, it is also unresponsive in-game. Given my breadth of games and to a lesser degree emulators relying on SDL2 (and they work fine), this is a peculiar issue. I tried throwing a gamecontrollerdb.txt at it to see if it'd read it/fix it, but no dice.

**Comment by sonik-br** [comment]
Same here on windows.
X360 and XOne controller does not work. DS4 and DS5 works fine.
SDL seems to detect the xbox devices but I could not get them to work.

**Comment by zaps166** [comment]
Hmm, I'll look at this later. @sonik-br I never used DS5 on Windows, do I need to install any drivers to get DS5 vibrations there?

Btw. unfortunately I don't use the controller DB in SDL2, maybe it could be a good idea to do it?

**Comment by sonik-br** [comment]
DS5 on windows 10 works native. I think it just uses the default HID driver.
Some games even supports the haptic trigger feedback!
I use mine over USB as I don't have Bluetooth.

**Comment by zaps166** [comment]
> Some games even supports the haptic trigger feedback!

Ok. I can use some haptics on Linux in Witcher 3 :smile: (only via USB).

**Comment by sonik-br** [comment]
Tested on windows...

DS and Xbox returns zero [here](https://github.com/zaps166/NFSIISE/blob/master/src/DInput.c#L273).
That's why here's no rumble anymore.

Xbox returns zero on SDL_JoystickGetAxis for axis 0, 1, 2, 3.
Axis 4 and 5 works. They are the L and R trigger.

Looks like a problem with SDL2.

**Comment by zaps166** [comment]
It's fixed on master, I'll release soon!
Thanks @sonik-br
